---
- name: Установка Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Создание DocumentRoot директории.
  ansible.builtin.file:
    path: "{{ nginx_document_root }}"
    state: directory
    mode: "755"
    owner: "{{ exec_user }}"

- name: Изменение nginx.conf по шаблону.
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: preserve
  notify:
    - Перезагрузка Nginx
  tags:
    - config

- name: Изменение default.conf по шаблону.
  ansible.builtin.template:
    src: localhost.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: preserve
  notify:
    - Перезагрузка Nginx
  tags:
    - config

- name: Копирование index.php файла.
  ansible.builtin.copy:
    src: index.php
    dest: "{{ nginx_document_root }}/index.php"
    mode: "777"
    owner: "{{ exec_user }}"
    group: "{{ exec_user }}"
  notify:
    - Перезагрузка Nginx
  tags:
    - config

- name: Запуск nginx сервиса
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
