---
- name: Установка php-fpm.
  ansible.builtin.apt:
    name: php-fpm
    state: present
    update_cache: true

- name: Проверка запуска php-fpm сервиса.
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true

- name: Настройка www-conf
  ansible.builtin.template:
    src: www-conf.j2
    dest: /etc/php/8.1/fpm/pool.d/www.conf
    mode: "644"
    owner: root
